snyk-fix-fd9cf3ac66ec85c373bd6fbe0c96f245
FROM tensorflow/tensorflow:latest-gpu
=======
snyk-fix-ec70dd212a8e05568da3cfb2776afa74
FROM tensorflow/tensorflow:2.8.2-gpu
=======
snyk-fix-7bb4d32fa7a3fce4accbeab2cdbc3155
FROM tensorflow/tensorflow:2.8.1-gpu
=======
snyk-fix-ef6aeaaced2c5932f1a22d63abab5cdf
FROM tensorflow/tensorflow:2.10.0rc1-gpu
=======
snyk-fix-7faf2c7d33a6657d4cdd5cee71ad886a
FROM tensorflow/tensorflow:latest-gpu
=======
snyk-fix-3297be71bbac68ee9e5d1a2826e5de83
FROM tensorflow/tensorflow:2.11.0rc1-gpu
=======
FROM tensorflow/tensorflow:2.12.0-gpu
master
master
master
master
master
master

RUN pip install numpy pandas scikit-learn dill dask distributed dask-ml keras
RUN mkdir /data
RUN mkdir /output
ENV PYTHONUNBUFFERED=0
COPY src /src
